---
- hosts: abode2
  become_user: root
  become_method: sudo
  tasks:
  - name: update apt cache if not done today
    apt: update_cache=yes cache_valid_time=86400
    notify:
      - Upgrade Pi
  - name: Install Git
    apt:
      pkg: git
  - name: Install XServer
    apt:
      pkg: xserver-xorg
  - name: Install xinit
    apt:
      pkg: xinit
  - name: Install mongodb-clients
    apt:
      pkg: mongodb-clients
  - name: Install mongodb-server
    apt:
      pkg: mongodb-server
  - name: Install omxplayer
    apt:
      pkg: omxplayer
  - name: Install gconf-service
    apt:
      pkg: gconf-service
  - name: Install libgtk2.0-0
    apt:
      pkg: libgtk2.0-0
  - name: Install libgnome-keyring0
    apt:
      pkg: libgnome-keyring0
  - name: Install libnspr4
    apt:
      pkg: libnspr4
  - name: Install libnspr4-0d
    apt:
      pkg: libnspr4-0d
  - name: Install libnss3
    apt:
      pkg: libnss3
  - name: Install libxss1
    apt:
      pkg: libxss1
  - name: Install xdg-utils
    apt:
      pkg: xdg-utils
  - name: Install Chromium
    apt:
      pkg: rpi-chromium-mods
  - name: Install Deja Fonts
    apt:
      pkg: fonts-dejavu-core
  - name: Install Dzen2
    apt:
      pkg: dzen2
  - name: Install Python AsyncIO
    apt:
      pkg: python-async
  - name: Install Apache2
    apt:
      pkg: apache2
  - name: Install libkrb5-dev
    apt:
      pkg: libkrb5-dev
  - name: node init
    notify:
    - Prep NodeJS
    copy:
      src: ansible_files/nodejs.sh
      dest: /root
      owner: root
      group: root
      mode: 0755
  - meta: flush_handlers
  - name: Install Node
    apt:
      pkg: nodejs
  - name: Install Bower
    shell: npm install --global bower
    args:
      creates: /usr/bin/bower
  - name: Install Forever
    shell: npm install --global forever
    args:
      creates: /usr/bin/forever
  - name: Add Scott User
    user:
      name: scott
      uid: 1001
  - name: Add Abode User
    user:
      name: abode
      uid: 1002
      groups: video,input,netdev
  - name: Add Scott Key
    authorized_key:
      user: scott
      key: "{{ lookup('file', '/home/scott/.ssh/id_rsa.pub') }}"
      path: '/home/scott/.ssh/authorized_keys'
      manage_dir: yes
  - name: Scott Sudoers
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^scott'
      line: 'scott ALL=(ALL) NOPASSWD: ALL'
  - name: Abobe Sudoers
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^abode'
      line: 'abode ALL=(ALL) NOPASSWD: /home/abode/abode-server/set_brightness'
  - name: Disable Pi
    user:
      name: pi
      password: '!!'
  - name: MOTD
    copy:
      src: ansible_files/etc/motd
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
  - name: SSHD Config
    notify:
    - Restart SSH
    copy:
      src: ansible_files/etc/ssh/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0644
  - name: Abode Display
    notify:
      - Restart Abode Display
    copy:
      src: abode-display.py
      dest: /usr/bin/abode-display.py
      owner: root
      group: root
      mode: 0755
  - name: Abode Display Service
    copy:
      src: abode-display.service
      dest: /lib/systemd/system/abode-display.service
      owner: root
      group: root
      mode: 0644
  - name: Abode Display Service Link
    file:
      src: /lib/systemd/system/abode-display.service
      dest: /etc/systemd/system/abode-display.service
      state: link
  - name: Start Abode Display
    service:
      name: abode-display
      enabled: yes
      state: started
  - name: Abode Service
    copy:
      src: abode.service
      dest: /lib/systemd/system/abode.service
      owner: root
      group: root
      mode: 0644
  - name: Abode Service Link
    file:
      src: /lib/systemd/system/abode.service
      dest: /etc/systemd/system/abode.service
      state: link
  - name: Abode Auto-Login Service
    copy:
      src: ansible_files/lib/systemd/system/abode-monitor@.service
      dest: /lib/systemd/system/abode-monitor@.service
      owner: root
      group: root
      mode: 0644
  - name: Abode Auto-Login Service Link
    file:
      src: /lib/systemd/system/abode-monitor@.service
      dest: /etc/systemd/system/getty.target.wants/getty@tty1.service
      state: link
  - name: abode bash_profile
    copy:
      src: ansible_files/home/abode/.bash_profile
      dest: /home/abode/.bash_profile
      owner: abode
      group: abode
      mode: 0644
  - name: abode bashrc
    copy:
      src: ansible_files/home/abode/.bashrc
      dest: /home/abode/.bashrc
      owner: abode
      group: abode
      mode: 0644
  - name: abode xsession
    copy:
      src: ansible_files/home/abode/.xsession
      dest: /home/abode/.xsession
      owner: abode
      group: abode
      mode: 0644
  - name: abode start.sh
    copy:
      src: ansible_files/home/abode/start.sh
      dest: /home/abode/start.sh
      owner: abode
      group: abode
      mode: 0755
  - name: scott bashrc
    copy:
      src: /home/scott/.bashrc
      dest: /home/scott/.bashrc
      owner: scott
      group: scott
      mode: 0644
  - name: scott bash_profile
    copy:
      src: /home/scott/.bash_profile
      dest: /home/scott/.bash_profile
      owner: scott
      group: scott
      mode: 0644
  - name: scott bash_profile
    file:
      path: /home/scott/bin
      owner: scott
      group: scott
      mode: 0755
      state: directory
  - name: scott prompt
    copy:
      src: /home/scott/bin/prompt
      dest: /home/scott/bin/prompt
      owner: scott
      group: scott
      mode: 0755
  - name: set_brightness
    copy:
      src: set_brightness
      dest: /usr/local/bin/set_brightness
      owner: root
      group: root
      mode: 0755
  - name: abode apache conf
    notify:
    - Restart HTTPD
    copy:
      src: ansible_files/etc/apache2/sites-available/000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf
      owner: root
      group: root
      mode: 0644
  - name: proxy conf
    notify:
    - Restart HTTPD
    file:
      src: ../mods-available/proxy.conf
      dest: /etc/apache2/mods-enabled/proxy.conf
      state: link
  - name: Keyboard
    copy:
      src: ansible_files/etc/default/keyboard
      dest: /etc/default/keyboard
      owner: root
      group: root
      mode: 0644
  - name: Timezone
    file:
      src: /usr/share/zoneinfo/America/Los_Angeles
      dest: /etc/localtime
      state: link
      force: true
  - name: Editor
    file:
      src: /usr/bin/vim.tiny
      dest: /etc/alternatives/editor
      state: link
  - name: Pico
    file:
      src: /usr/bin/vim.tiny
      dest: /etc/alternatives/pico
      state: link
  - name: proxy_http conf
    notify:
    - Restart HTTPD
    file:
      src: ../mods-available/proxy_http.load
      dest: /etc/apache2/mods-enabled/proxy_http.load
      state: link
  - name: proxy.load
    notify:
    - Restart HTTPD
    file:
      src: ../mods-available/proxy.load
      dest: /etc/apache2/mods-enabled/proxy.load
      state: link
  - name: node link
    file:
      src: /usr/bin/nodejs
      dest: /usr/bin/node
      state: link
  - name: Start HTTPD
    tags: httpd
    service:
      name: apache2
      enabled: yes
      state: started
  - name: Start Mongo
    tags: mongo
    service:
      name: mongodb
      enabled: yes
      state: started
  - name: Clone Abode UI
    become: yes
    become_user: abode
    notify:
    - UI NPM Install
    git:
      repo: https://github.com/truesneel/abode-ui.git
      dest: /home/abode/abode-ui
      umask: '0002'
  - name: Clone Abode Server
    become: yes
    become_user: abode
    notify:
    - Server NPM Install
    - Restart Abode
    git:
      repo: https://github.com/truesneel/abode-server.git
      dest: /home/abode/abode-server
      umask: '0002'
  - name: Abode Server Access Log Directory
    file:
      path: /home/abode/abode-server/logs
      owner: abode
      group: abode
      state: directory
      mode: 0775
  - name: Start Abode
    tags: abode
    service:
      name: abode
      enabled: yes
      state: started
  handlers:
    - name: Upgrade Pi
      shell: /usr/bin/apt-get upgrade
    - name: Restart HTTPD
      service:
        name: apache2
        state: restarted
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
    - name: UI NPM Install
      become: yes
      become_user: abode
      shell: /usr/bin/npm install
      args:
        chdir: /home/abode/abode-ui
    - name: Server NPM Install
      become: yes
      become_user: abode
      shell: /usr/bin/npm install
      args:
        chdir: /home/abode/abode-server
    - name: Restart Abode
      service:
        name: abode
        state: restarted
    - name: Restart Abode Display
      service:
        name: abode-display
        state: restarted
    - name: Prep NodeJS
      shell: /root/nodejs.sh

